### ISSUE TITLE
Cannot compile 'win_delay_load_hook.c' with the /ZW option

### ISSUE THREAD

**Issue by CharlieHess** [CatalystCode/electron-windows-notifications#9]
During `node-gyp rebuild` on Windows 10:
```
cl : Command line error D8048: cannot compile C file 'C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c' with the /ZW option [C:\Source\slack-winssb\node_modules\@nodert-win10\windows.ui.notifications\build\binding.vcxproj]
```
Any ideas?

**Comment by nadavbar** [comment]
@CharlieHess This issue was resolved in newer versions of npm that the node.js installer hasn't picked up yet. They basically renamed the c file to a cc extension.   You can resolve it by running 
npm install -g npm@next

**Comment by CharlieHess** [comment]
@nadavbar thanks for the heads up, that fixed it.
